fluidPage(
    titlePanel("Coursera's Data Science Capstone - NLP"),
    hr(),
    sidebarLayout(
        # Instructions sidebar
        sidebarPanel(
            h4("How to use:"),
            p("Is simple, just start typing at your heart content on the box 'Your input'"),
            p("As you type a list of predicted words will be shown as options under the box, 
if you click on one of them it will be automatically added to your input box and a new set of predictions will be generated."),
            p("There are two types of predictions, 'new word' prediction which are generated after you type an space; 
and 'completion' prediction which are generated as you type a word; On both cases the order of predicted words is
determined by the language model generated by our algorithm, hopefully giving you the most relevant options first."),
            br(),
            p("To the right of the predicted words you can find a 'word cloud' that represents with varying sizes and colors the 
relative relevance of a word prediction, you can control the number of words in the cloud using the provided slider."),
            p("In order to provide responsive predictions as you type, the word cloud is not automatically updated, 
feel free to use the button 'Refresh word cloud' to update it. A caveat on it, word cloud shows only 'new word' predictions
so if you are typing a word and try to update the cloud, then terms on it won't match the options in the list, 
since those in the list are 'completion' predictions."),
            br(),
            h4("Bonus!"),
            p("If you don't feel like typing or just want to see what kind of non-sense our algorithm can say, 
then let us generate random rants for you by using the button 'Generate a random rant', you can also type something on the provided
textbox to get started the ranting about a topic you want."),
            p("Please note that our algorithm doesn't have context awarenes and will change topics like a random rant ;)"),
            br(),
            h4("Source code?"),
            p("That's on me, with the proper attributions:"),
            a("Github repo", href="https://github.com/aguereca/CapstoneProject-NLP/tree/master/code/shiny_app", target="_blank"),
            
            hr(),
            h5("Credits:"),
            actionLink('git', icon=icon('github'), label="github.com/aguereca"),
            br(),
            actionLink('git', icon=icon('linkedin'), label="linkedin.com/in/armandoguereca")
        ),
        
        # Main content page
        mainPanel(
            tabsetPanel(type = "tabs", selected = "Prediction",
                        tabPanel("Prediction",
                                 uiOutput("header_panel"),
                                 br(),
                                 textInput("usr_input", "Your input:", "Data science is "),
                                 hr(),
                                 fluidRow(
                                     column(width = 4,
                                            radioButtons("pred_options", label = h5("Top 10 predictions:"),
                                                         choices = list(), 
                                                         selected = 1, inline=T),
                                            br(),
                                            actionButton("ref_cloud", "Refresh word cloud", align="right")
                                 
                                    ),
                                    column(width = 6, offset=1,
                                           h5("Word cloud of predictions:"),
                                           plotOutput("word_plot"),
                                           sliderInput("max_words", "Words on cloud:",
                                                       min = 10,  max = 150,  value = 75)
                                    )
                                 ),
                                 hr(),
                                 textInput("rant_seed", "Rant me about...", "Unicorns myth: "),
                                 actionButton("rand_rant", "Generate a new random rant !"),
                                 br(),
                                 br(),
                                 verbatimTextOutput("rant_text"),
                                 hr()
                        ),
                        tabPanel("Documentation",
                                 br()
                        )
            )
        )
    )
)