# Source: https://en.wikipedia.org/wiki/Wikipedia:List_of_English_contractions
# Horizontal matrix of common english contractions
contractions <- matrix(
c(
    c("ain't", "am not"),
    c("aren't", "are not"),
    c("can't", "can not"),
    c("could've", "could have"),
    c("couldn't", "could not"),
    c("couldn't've", "could not have"),
    c("didn't", "did not"),
    c("doesn't", "does not"),
    c("don't", "do not"),
    c("gonna", "going to"),
    c("hadn't", "had not"),
    c("hadn't've", "had not have"),
    c("hasn't", "has not"),
    c("haven't", "have not"),
    c("he'd", "he would"),
    c("he'd've", "he would have"),
    c("he'll", "he will"),
    c("he's", "he is"),
    c("he'sn't", "he is not"),
    c("how'd", "how would"),
    c("how'll", "how will"),
    c("how's", "how is"),
    c("I'd", "I would"),
    c("I'd've", "I would have"),
    c("I'll", "I will"),
    c("I'm", "I am"),
    c("I've", "I have"),
    c("I'ven't", "I have not"),
    c("isn't", "is not"),
    c("it'd", "it would"),
    c("it'd've", "it would have"),
    c("it'll", "it will"),
    c("it's", "it is"),
    c("it'sn't", "it is not"),
    c("let's", "let us"),
    c("ma'am", "madam"),
    c("mightn't", "might not"),
    c("mightn't've", "might not have"),
    c("might've", "might have"),
    c("mustn't", "must not"),
    c("must've", "must have"),
    c("needn't", "need not"),
    c("not've", "not have"),
    c("o'clock", "of the clock"),
    c("oughtn't", "ought not"),
    c("shan't", "shall not"),
    c("she'd", "she would"),
    c("she'd've", "she would have"),
    c("she'll", "she will"),
    c("she's", "she is"),
    c("she'sn't", "she is not"),
    c("should've", "should have"),
    c("shouldn't", "should not"),
    c("shouldn't've", "should not have"),
    c("somebody'd", "somebody would"),
    c("somebody'd've", "somebody would have"),
    c("somebody'dn't've", "somebody would not have"),
    c("somebody'll", "somebody will"),
    c("somebody's", "somebody is"),
    c("someone'd", "someone would"),
    c("someone'd've", "someone would have"),
    c("someone'll", "someone will"),
    c("someone's", "someone is"),
    c("something'd", "something would"),
    c("something'd've", "something would have"),
    c("something'll", "something will"),
    c("something's", "something is"),
    c("that'll", "that will"),
    c("that's", "that is"),
    c("there'd", "there would"),
    c("there'd've", "there would have"),
    c("there're", "there are"),
    c("there's", "there is"),
    c("they'd", "they would"),
    c("they'dn't", "they would not"),
    c("they'dn't've", "they would not have"),
    c("they'd've", "they would have"),
    c("they'd'ven't", "they would have not"),
    c("they'll", "they will"),
    c("they'lln't've", "they will not have"),
    c("they'll'ven't", "they will have not"),
    c("they're", "they are"),
    c("they've", "they have"),
    c("they'ven't", "they have not"),
    c("'tis", "it is"),
    c("'twas", "it was"),
    c("wanna", "want to"),
    c("wasn't", "was not"),
    c("we'd", "we would"),
    c("we'd've", "we would have"),
    c("we'dn't've", "we would not have"),
    c("we'll", "we will"),
    c("we'lln't've", "we will not have"),
    c("we're", "we are"),
    c("we've", "we have"),
    c("weren't", "were not"),
    c("what'll", "what will"),
    c("what're", "what are"),
    c("what's", "what is"),
    c("what've", "what have"),
    c("when's", "when is"),
    c("where'd", "where did"),
    c("where's", "where is"),
    c("where've", "where have"),
    c("who'd", "who would"),
    c("who'd've", "who would have"),
    c("who'll", "who will"),
    c("who're", "who are"),
    c("who's", "who is"),
    c("who've", "who have"),
    c("why'll", "why will"),
    c("why're", "why are"),
    c("why's", "why is"),
    c("won't", "will not"),
    c("won't've", "will not have"),
    c("would've", "would have"),
    c("wouldn't", "would not"),
    c("wouldn't've", "would not have"),
    c("y'all", "you all"),
    c("y'all'd've", "you all would have"),
    c("y'all'dn't've", "you all would not have"),
    c("y'all'll", "you all will"),
    c("y'all'll've", "you all will have"),
    c("y'all'll'ven't", "you all will have not"),
    c("you'd", "you would"),
    c("you'd've", "you would have"),
    c("you'll", "you will"),
    c("you're", "you are"),
    c("you'ren't", "you are not"),
    c("you've", "you have"),
    c("you'ven't", "you have not")
), nrow=2)

expand_contractions <- function(text) {
    # Normalize apostrophes
    text <- gsub('’', "'", text)
    for (col in seq(ncol(contractions))) {
        text <- gsub(contractions[1, col], contractions[2, col], text)
    }
    return(text)
}